// src/components/ComingSoon.jsx
import { useNavigate } from "react-router-dom";

export default function ComingSoon() {
  const navigate = useNavigate();

  return (
    <div className="not-found">
      <h2 className="not-found-code">Soon</h2>
      <p className="not-found-message">This page is still being assembled.</p>
      <button className="not-found-back" onClick={() => navigate("/")}>
        &lt; go back home
      </button>
    </div>
  );
}

// src/components/ComingSoon.svelte
<script>
  import { navigate } from "svelte-routing";
</script>

<div class="not-found">
  <h2 class="not-found-code">Soon</h2>
  <p class="not-found-message">This page is still being assembled.</p>
  <button class="not-found-back" onclick={() => navigate("/")}>
    &lt; go back home
  </button>
</div>
