// src/components/ProjectCarousel.jsx
import { useRef, useEffect, useState } from "react";
import ProjectCard from "./ProjectCard";
import "./ProjectCarousel.css";

export default function ProjectCarousel({ projects }) {
  const trackRef = useRef(null);
  const [progress, setProgress] = useState(0);

  useEffect(() => {
    const track = trackRef.current;
    if (!track) return;
    const onScroll = () => {
      const max = track.scrollWidth - track.clientWidth;
      setProgress(max > 0 ? track.scrollLeft / max : 0);
    };
    track.addEventListener("scroll", onScroll, { passive: true });
    return () => track.removeEventListener("scroll", onScroll);
  }, []);

  return (
    <div className="carousel-wrapper">
      <div className="carousel-track" ref={trackRef}>
        {projects.map((project, i) => (
          <ProjectCard key={project.id} project={project} index={i} />
        ))}
      </div>

      {/* Progress bar */}
      <div className="carousel-progress-bar">
        <div
          className="carousel-progress-fill"
          style={{ width: `${progress * 100}%` }}
        />
      </div>

    </div>
  );
}

// src/components/ProjectCarousel.svelte
<script>
  import { onMount } from "svelte";
  import ProjectCard from "./ProjectCard.svelte";
  import "./ProjectCarousel.css";

  export let projects = [];

  let trackRef;
  let progress = 0;

  function onScroll() {
    if (!trackRef) return;
    const max = trackRef.scrollWidth - trackRef.clientWidth;
    progress = max > 0 ? trackRef.scrollLeft / max : 0;
  }

  onMount(() => {
    if (trackRef) {
      trackRef.addEventListener("scroll", onScroll, { passive: true });
    }
    return () => {
      if (trackRef) {
        trackRef.removeEventListener("scroll", onScroll);
      }
    };
  });
</script>

<div class="carousel-wrapper">
  <div class="carousel-track" bind:this={trackRef}>
    {#each projects as project, i (project.id)}
      <ProjectCard {project} index={i} />
    {/each}
  </div>

  <!-- Progress bar -->
  <div class="carousel-progress-bar">
    <div
      class="carousel-progress-fill"
      style="width: {progress * 100}%;"
    ></div>
  </div>
</div>
