// src/components/ThemeToggle.svelte
<script>
  let dark = $state(true);

  $effect(() => {
    document.documentElement.setAttribute(
      "data-theme",
      dark ? "dark" : "light"
    );
  });
</script>

<button
  class="theme-toggle"
  onclick={() => dark = !dark}
  aria-label="Toggle light/dark mode"
>
  {dark ? "light" : "dark"}
</button>

// src/components/ThemeToggle.jsx
import { useState, useEffect } from "react";

export default function ThemeToggle() {
  const [dark, setDark] = useState(true);

  useEffect(() => {
    document.documentElement.setAttribute(
      "data-theme",
      dark ? "dark" : "light"
    );
  }, [dark]);

  return (
    <button
      className="theme-toggle"
      onClick={() => setDark((d) => !d)}
      aria-label="Toggle light/dark mode"
    >
      {dark ? "light" : "dark"}
    </button>
  );
}
