// src/App.svelte
<script>
      import MenuOverlay from "./components/MenuOverlay.svelte";
  import ThemeToggle from "./components/ThemeToggle.svelte";
  import Cursor from "./components/Cursor.svelte";
  import AsciiBackground from "./components/AsciiBackground.svelte";

  import Bio from "./components/Bio.svelte";
  import Skills from "./components/Skills.svelte";
  import Projects from "./components/Projects.svelte";
  import Contact from "./components/Contact.svelte";
  import NotFound from "./components/NotFound.svelte";
  import ComingSoon from "./components/ComingSoon.svelte";
  import Quote from "./components/Quote.svelte";
  import HeroName from "./components/HeroName.svelte";
  import HalftoneImage from "./components/HalftoneImage.svelte";
  import Home from "./components/Home.svelte";
  import MediaLibrary from "./components/MediaLibrary.svelte";
  import Questions from "./components/Questions.svelte";

  import { quoteStore } from "./stores/quote.svelte.js";
  import "./App.css";


  let currentPath = $state(window.location.pathname);


  const KNOWN_ROUTES = [
    "/", "/about", "/skills", "/projects", "/contact",
    "/now", "/colophon", "/minis", "/media-library",
    "/questions",
  ];

  const HIDE_PORTRAIT = ["/skills", "/projects"];

  let isKnown = $derived(KNOWN_ROUTES.includes(currentPath));
  let currentView = $derived(currentPath.slice(1));
  let showPortrait = $derived(!HIDE_PORTRAIT.includes(currentPath));
  let contentFill = $derived(currentPath === "/projects" || currentPath === "/skills");
</script>

  {#if !isKnown}
    <div class="with-frame">
      <AsciiBackground />
      <NotFound />
      <Cursor />
    </div>
  {:else if currentPath === "/media-library"}
    <MediaLibrary />
    <MenuOverlay view="media-library" />
    <Cursor />
  {:else if currentPath === "/"}
    <div class="page-content with-frame">
      <AsciiBackground />
      <Home />
      <div class="home-name-overlay">
        <HeroName />
        <Quote displayed={quoteStore.displayed} phase={quoteStore.phase} onCycle={quoteStore.cycleQuote} />
      </div>
    </div>
    <MenuOverlay view="home" />
    <Cursor />
  {:else if currentPath === "/questions"}
    <Questions />
    <Cursor />
  {:else}
    <div class="page page-content with-frame {showPortrait ? '' : 'no-portrait'}">
      <AsciiBackground />

      <!-- Name + Quote group — top-left -->
      <div class="name-group">
        <footer class="bottom-bar">
          <HeroName />
        </footer>
        <Quote displayed={quoteStore.displayed} phase={quoteStore.phase} onCycle={quoteStore.cycleQuote} />
      </div>

      <!-- Portrait — bottom-left (hidden on skills/projects) -->
      {#if showPortrait}
        <div class="portrait-column">
          <HalftoneImage
            src="/portraits/tower.jpg"
            alt="Ark Malhotra portrait"
            class="portrait"
          />
        </div>
      {/if}

      <!-- Content — bottom-right, swaps based on route -->
      <main class="content {contentFill ? 'content--fill' : ''}">
        {#if currentPath === "/about"} <Bio /> {/if}
        {#if currentPath === "/skills"} <Skills /> {/if}
        {#if currentPath === "/projects"} <Projects /> {/if}
        {#if currentPath === "/contact"} <Contact /> {/if}
        {#if currentPath === "/now"} <ComingSoon /> {/if}
        {#if currentPath === "/colophon"} <ComingSoon /> {/if}
        {#if currentPath === "/minis"} <ComingSoon /> {/if}
      </main>
    </div>

    <!-- Menu — hamburger button fixed top-right, opens full-screen bento overlay -->
    <MenuOverlay view={currentView} />

    <!-- Custom cursor -->
    <Cursor />
  {/if}

// src/App.jsx
import { Routes, Route, useLocation } from "react-router-dom";
import MenuOverlay from "./components/MenuOverlay";
import ThemeToggle from "./components/ThemeToggle";
import Cursor from "./components/Cursor";
import AsciiBackground from "./components/AsciiBackground";

import Bio from "./components/Bio";
import Skills from "./components/Skills";
import Projects from "./components/Projects";
import Contact from "./components/Contact";
import NotFound from "./components/NotFound";
import ComingSoon from "./components/ComingSoon";
import Quote from "./components/Quote";
import HeroName from "./components/HeroName";
import HalftoneImage from "./components/HalftoneImage";
import Home from "./components/Home";
import { useQuote } from "./hooks/useQuote";
import "./App.css";

// Known React routes — everything else is a 404
const KNOWN_ROUTES = [
  "/", "/about", "/skills", "/projects", "/contact",
  "/now", "/colophon", "/minis", "/media-library",
];

// Pages where the portrait should be hidden
const HIDE_PORTRAIT = ["/skills", "/projects"];

function App() {
  const location = useLocation();
  const quote = useQuote();

  const isKnown = KNOWN_ROUTES.includes(location.pathname);

  // 404 gets its own minimal layout — no name, no portrait, no quote
  if (!isKnown) {
    return (
      <>
        <AsciiBackground />
        <NotFound />
        {/* <ThemeToggle /> */}
        <Cursor />
      </>
    );
  }

  // Home gets a full-screen layout — canvas + name/quote overlay + nav + cursor
  if (location.pathname === "/") {
    return (
      <>
        <AsciiBackground />
        <Home />
        <div className="home-name-overlay">
          <HeroName />
          <Quote displayed={quote.displayed} phase={quote.phase} onCycle={quote.cycleQuote} />
        </div>
        <MenuOverlay view="home" />
        {/* <ThemeToggle /> */}
        <Cursor />
      </>
    );
  }

  // Derive the current nav key from the pathname for menu highlighting
  const currentView = location.pathname.slice(1); // "about", "skills", "projects", "contact", etc.

  const showPortrait = !HIDE_PORTRAIT.includes(location.pathname);

  return (
    <div className={`page${showPortrait ? "" : " no-portrait"}`}>
      <AsciiBackground />
      {/* Name + Quote group — top-left */}
      <div className="name-group">
        <footer className="bottom-bar">
          <HeroName />
        </footer>
        <Quote displayed={quote.displayed} phase={quote.phase} onCycle={quote.cycleQuote} />
      </div>

      {/* Portrait — bottom-left (hidden on skills/projects) */}
      {showPortrait && (
        <div className="portrait-column">
          <HalftoneImage
            src="/portraits/tower.jpg"
            alt="Ark Malhotra portrait"
            className="portrait"
          />
        </div>
      )}

      {/* Content — bottom-right, swaps based on route */}
      <main className={`content${location.pathname === "/projects" || location.pathname === "/skills" ? " content--fill" : ""}`} key={location.pathname}>
        <Routes>
          <Route path="/about"         element={<Bio />} />
          <Route path="/skills"        element={<Skills />} />
          <Route path="/projects"      element={<Projects />} />
          <Route path="/contact"       element={<Contact />} />
          <Route path="/now"           element={<ComingSoon />} />
          <Route path="/colophon"      element={<ComingSoon />} />
          <Route path="/minis"         element={<ComingSoon />} />
          <Route path="/media-library" element={<ComingSoon />} />
        </Routes>
      </main>

      {/* Menu — hamburger button fixed top-right, opens full-screen bento overlay */}
      <MenuOverlay view={currentView} />

      {/* Theme toggle — intentionally disabled, light mode unimplemented */}
      {/* <ThemeToggle /> */}

      {/* Custom cursor */}
      <Cursor />
    </div>
  );
}

export default App;
